apiVersion: v1
kind: Service
metadata:
  name: java-guestbook-gateway
  labels:
    app: java-guestbook
    tier: gateway
spec:
  type: LoadBalancer
  selector:
    app: java-guestbook
    tier: gateway
  ports:
    - port: 8080
      targetPort: http-server
